- name: Install ruby and bundler
  hosts: all
  become: true
  tasks:
    - name: Install a list of required packages
      apt:
        pkg:
        - ruby-full
        - ruby-bundler
        - build-essential
