- name: Install MongoDB
  hosts: all
  become: true
  tasks:
    - name: Add repo key
      apt_key:
        url: https://www.mongodb.org/static/pgp/server-3.2.asc
        state: present
    - name: Add repo
      apt_repository:
        repo: deb [ arch=amd64,arm64] http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.2 multiverse
        state: present
        update_cache: yes
    - name: Install mongodb
      apt:
        name: mongodb-org
        state: present
    - name: Enable mongod
      systemd:
        name: mongod
        enabled: yes
